version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /terraform/examples/complete/foundation
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /terraform/examples/complete/addons
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /docker/lore
    schedule:
      interval: weekly
