apiVersion: v1
kind: ServiceAccount
metadata:
  name: lore-edge
  namespace: lore
  labels:
    {{- include "lore.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lore-write
  namespace: lore
  labels:
    {{- include "lore.labels" . | nindent 4 }}
    app.kubernetes.io/component: write
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lore-otel
  namespace: lore
  labels:
    {{- include "lore.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry
automountServiceAccountToken: true
