apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.name }}
  annotations:
    kubernetes.io/description: "AL2023 nodes for {{ .Values.nodePool.name }}"
spec:
  role: {{ .Values.nodeClass.role | quote }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.nodeClass.discoveryTagValue | quote }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.nodeClass.discoveryTagValue | quote }}
  amiSelectorTerms:
    - alias: {{ .Values.nodeClass.amiAlias | quote }}
  associatePublicIPAddress: false
  detailedMonitoring: false
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: {{ printf "%vGi" .Values.nodeClass.rootVolumeSize | quote }}
        volumeType: gp3
        iops: 3000
        throughput: 125
        {{- with .Values.nodeClass.rootVolumeKmsKey }}
        kmsKeyID: {{ . | quote }}
        {{- end }}
  tags:
    {{- toYaml .Values.nodeClass.tags | nindent 4 }}
